trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  environment: 'Production'
  applicationVersion: 0.0

name: $(applicationVersion).$(Rev:r)

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
    - job: 'Prerequisites'
      displayName: 'Prerequisites for Build'
      steps:
      - task: DotNetCoreCLI@2
        displayName: Add Manifest for tool installation
        inputs:
          command: 'custom'
          custom: 'new'
          arguments: tool-manifest
      - task: DotNetCoreCLI@2
        displayName: Install EF Tool
        inputs:
          command: 'custom'
          custom: 'tool '
          arguments: install dotnet-ef
    - job: 'Build'
      displayName: 'Build'
      steps:
      - script: |
          dotnet restore -r win-x64
          echo Building application version $(ApplicationVersion) $(Build.BuildNumber).
          dotnet build --no-incremental --no-self-contained --configuration $(buildConfiguration) --no-restore -p:Version=$(ApplicationVersion) -p:FileVersion=$(Build.BuildNumber) -p:MarushRuntime=win-x64
        displayName: '.Net Core Build'
    - job: 'Artifacts'
      displayName: 'Publishing Artifacts'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Packing artifacts'
        inputs:
          command: 'publish'
          configuration: $(BuildConfiguration)
          nobuild: True 
          publishWebProjects: True
          arguments: -r win-x64 --no-self-contained --output $(Build.ArtifactStagingDirectory) -p:EnvironmentName=$(environment) -p:Version=$(ApplicationVersion) -p:FileVersion=$(Build.BuildNumber) -p:MarushRuntime=win-x64
          zipAfterPublish: True
      - task: PublishBuildArtifacts@1
        displayName: 'Publishing artifacts'
        inputs:
          ArtifactName: Marush
- stage: 'DeployToTest'
  displayName: 'Deploy to Test'
  dependsOn: 'Build'
  condition:  succeeded()
  jobs:
    - template: 'Deployment/Templates/environment-deploy.yaml'
      parameters:
        deploymentName: 'DeployToTest'
        environment: 'Test'
        destinationWebsiteName: MarushTest
