trigger: none

schedules:
- cron: '0 12 * * 0'
  displayName: Weekly Sunday build
  branches:
    include:
    - main
  always: false

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore Packages'
    inputs:
      command: 'restore'
      projects: '**/*.sln'
  - task: SonarQubePrepare@5
    displayName: 'Prepare SonarQube analysis'
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: 'MSBuild'
      projectKey: 'Marush'
      projectName: 'Marush'
      extraProperties: 'sonar.coverageReportPaths=coveragereport/SonarQube.xml'
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.sln'
  - powershell: |
      $params = "$env:SONARQUBE_SCANNER_PARAMS" -replace '"sonar.branch.name":"[\w,/,-]*"\,?'
      Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"
    displayName: 'Fixing Sonar Branch'
  - task: SonarQubeAnalyze@5
    displayName: 'Run SonarQube analysis'
  - task: SonarQubePublish@5
    displayName: 'Publish SonarQube analysis'
    inputs:
      pollingTimeoutSec: '300'
