parameters:
- name: dotNetVersion
- name: applicationVersion
- name: angularApplicationPath
- name: apiApplicationPath
- name: migrationsAssemblyPath
- name: buildConfiguration
  default: 'Release'
- name: environment
  default: 'Production'
- name: dbContextName
  default: 'MarushCareContext'
- name: artifactName
  default: 'Marush'

jobs:
 - job: 'Build'
   displayName: 'Build'
   steps:
      - task: UseDotNet@2
        displayName: 'Set .Net version'
        inputs:
          version: ${{ parameters.dotNetVersion }}
      - task: Npm@1
        displayName: 'Install node modules'
        inputs:
          command: 'ci'
          workingDir: ${{ parameters.angularApplicationPath }}
      - task: Npm@1
        displayName: 'Execute Linting'
        inputs:
          command: 'custom'
          customCommand: 'run lint'
          workingDir: ${{ parameters.angularApplicationPath }}   
      - task: Npm@1
        displayName: 'Building Angular Application'
        inputs:
          command: 'custom'
          customCommand: 'run build --configuration=production'
          workingDir: ${{ parameters.angularApplicationPath }}
      - task: DotNetCoreCLI@2
        displayName: 'Add Manifest for tool installation'
        inputs:
          command: 'custom'
          custom: 'new'
          arguments: tool-manifest
      - task: DotNetCoreCLI@2
        displayName: 'Install EF Tool'
        inputs:
          command: 'custom'
          custom: 'tool '
          arguments: install dotnet-ef
      - task: DotNetCoreCLI@2
        displayName: 'Install workload for Aspire'
        inputs:
          command: 'custom'
          custom: 'workload'
          arguments: 'install aspire'
      - task: DotNetCoreCLI@2
        displayName: 'Restoring NuGet Packages'
        inputs:
          command: 'custom'
          custom: 'restore'
          arguments: '-r win-x64'
      - task: DotNetCoreCLI@2
        displayName: '.Net Core Build'
        inputs:
          command: 'custom'
          custom: 'build'
          arguments: '--no-incremental --no-self-contained --configuration ${{ parameters.buildConfiguration }} --no-restore -p:Version=${{ parameters.applicationVersion }} -p:FileVersion=$(Build.BuildNumber) -p:MarushRuntime=win-x64'
      - task: DotNetCoreCLI@2
        displayName: Create Entity Framework's Bundle for SQL
        inputs:
          command: 'custom'
          workingDirectory: Site/${{ parameters.apiApplicationPath }}
          custom: 'ef '
          arguments: migrations bundle --output $(Build.ArtifactStagingDirectory)\Migrations\${{ parameters.dbContextName }}-efbundle.exe --project ${{ parameters.migrationsAssemblyPath }} --startup-project ./${{ parameters.apiApplicationPath }}.csproj --context ${{ parameters.dbContextName }} --configuration ${{ parameters.buildConfiguration }} --runtime win-x64 --force --verbose     
      - task: DotNetCoreCLI@2
        displayName: 'Packing artifacts'
        inputs:
          command: 'publish'
          configuration: ${{ parameters.buildConfiguration }}
          nobuild: True 
          publishWebProjects: True
          arguments: -r win-x64 --no-self-contained --output $(Build.ArtifactStagingDirectory) -p:EnvironmentName=${{ parameters.environment }} -p:Version=${{ parameters.applicationVersion }} -p:FileVersion=$(Build.BuildNumber) -p:MarushRuntime=win-x64
          zipAfterPublish: True
      - task: PublishBuildArtifacts@1
        displayName: 'Publishing artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: ${{ parameters.artifactName }}-$(Build.BuildNumber)
          publishLocation: 'Container'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish SQL artifacts - appsettings.json'
        inputs:
          PathtoPublish: $(Build.SourcesDirectory)/Site/${{ parameters.apiApplicationPath }}/appsettings.json
          ArtifactName: ${{ parameters.artifactName }}-$(Build.BuildNumber)
          publishLocation: $(Build.ArtifactStagingDirectory)\Migrations
      - task: CmdLine@2
        displayName: 'Reset local changes'
        inputs:
          script: 'git reset --hard'