parameters:
- name: deploymentName
- name: destinationWebsiteName
- name: environment
- name: projectName
  default: 'Marush'
- name: approvalJobName
  default: ''
- name: resourceName
  default: VMI1461179
- name: archiveFile
  default: 'Gmf.Marush.Care.App.zip'
- name: artifactName
  default: Marush

jobs:
  - deployment: ${{ parameters.deploymentName }}
    displayName: 'Executing ${{ parameters.deploymentName }} '
    ${{ if ne(parameters.approvalJobName, '') }}:
      dependsOn: ${{ parameters.approvalJobName }}
    condition: or(eq('${{ parameters.approvalJobName }}', ''), succeeded('${{ parameters.approvalJobName }}'))
    variables:
    - name: environment
      value: ${{ parameters.environment }}
    - template: ../Variables/${{ parameters.environment }}-variables.yaml 
    environment: 
      name: ${{ parameters.environment }}
      resourceName: ${{ parameters.resourceName }}
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download artifact
            inputs:
              buildType: 'current'
              artifactName: '${{ parameters.artifactName }}-$(Build.BuildNumber)'
              targetPath: '$(Pipeline.Workspace)'
          - task: ExtractFiles@1
            displayName: 'Extract ${{ parameters.projectName }} Artifacts'
            inputs:
              archiveFilePatterns: '$(Agent.BuildDirectory)/${{ parameters.projectName }}-$(Build.BuildNumber)/${{ parameters.archiveFile }}'
              destinationFolder: '$(Agent.BuildDirectory)/${{ parameters.projectName }}/Temp/App'
            retryCountOnTaskFailure: 3
          - task: PowerShell@2
            displayName: 'Copy Robots.txt'
            inputs:
                targetType: inline
                script: Copy-Item -Path "$(Agent.BuildDirectory)/${{ parameters.projectName }}/Temp/App/Properties/Robots.$(environment).txt" -Destination "$(Agent.BuildDirectory)/${{ parameters.projectName }}/Temp/App/robots.txt"
          - task: qetza.replacetokens.replacetokens-task.replacetokens@6
            displayName: 'Tokens replacement'
            inputs:
              root: '$(Agent.BuildDirectory)/${{ parameters.projectName }}/Temp'
              sources: |
                **/dist/**/*.js
                **/dist/**/*.mjs
                **/web.config
                **/appsettings.json
              tokenPattern: custom
              tokenPrefix: '_-_-'
              tokenSuffix: '-_-_'
              keepToken: true
              missingVarLog: off
          - task: ArchiveFiles@2
            displayName: 'Pack ${{ parameters.projectName }} ${{ parameters.deploymentName }}'
            inputs:
              rootFolderOrFile: '$(Agent.BuildDirectory)/${{ parameters.projectName }}/Temp/App'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.archiveFile }}'
              retryCountOnTaskFailure: 3
          - script: |
              msdeploy.exe -source:contentPath="$(Agent.BuildDirectory)\${{ parameters.projectName }}\Temp\App\Properties\app_offline_template.htm" -dest:contentPath='${{ parameters.destinationWebsiteName }}\app_offline.htm' –verb:sync -disablerule:BackupRule
            displayName: 'Put App Offline page'
            retryCountOnTaskFailure: 3
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'Trigger built-in backup & Deploy ${{ parameters.projectName }} ${{ parameters.deploymentName }}'
            inputs:
              WebSiteName: ${{ parameters.destinationWebsiteName }}
              Package: '$(Build.ArtifactStagingDirectory)/${{ parameters.archiveFile }}'
              retryCountOnTaskFailure: 3
          - script: |
              msdeploy.exe -dest:contentPath='${{ parameters.destinationWebsiteName }}/app_offline.htm' –verb:delete -disablerule:BackupRule
            workingDirectory: 'C:\Program Files\IIS\Microsoft Web Deploy V3\'
            failOnStderr: true
            displayName: 'Remove App Offline pages'
            retryCountOnTaskFailure: 3 
  - job: 'CleanUp${{ parameters.deploymentName }}'
    displayName: 'Clean up ${{ parameters.deploymentName }}'
    dependsOn: ${{ parameters.deploymentName }}
    steps:
      - task: DeleteFiles@1
        displayName: 'Delete files from Temp'
        inputs:
          SourceFolder: '$(Agent.BuildDirectory)/${{ parameters.projectName }}/Temp'
          Contents: Gmf
          RemoveSourceFolder: true
        retryCountOnTaskFailure: 3
