parameters:
- name: dbContextName
- name: migrationConnectionString
- name: artifactName
  default: 'Marush'
- name: environment
- name: resourceName
  default: VMI1461179
- name: approvalJobName
  default: ''

jobs:
- job: 'update_databases'
  ${{ if ne(parameters.approvalJobName, '') }}:
    dependsOn: ${{ parameters.approvalJobName }}
    condition: or(eq('${{ parameters.approvalJobName }}', ''), succeeded('${{ parameters.approvalJobName }}'))
  displayName: 'Update Database'
  pool: ${{ parameters.environment }}
  steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      displayName: Download migrations artifact
      inputs:
        buildType: 'current'
        artifactName: '${{ parameters.artifactName }}-migrations-$(Build.BuildNumber)'
        targetPath: '$(Pipeline.Workspace)'
    - task: CmdLine@2
      displayName: Execute migrations
      inputs:
        script: $(Pipeline.Workspace)\${{ parameters.dbContextName }}-efbundle.exe --connection "${{ parameters.migrationConnectionString }}"