trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  applicationVersion: 0.3
  dotNetVersion: 8.0.100
  angularApplicationPath: '$(Build.SourcesDirectory)/Site/Gmf.Marush.Care.App'

name: $(applicationVersion).$(Rev:r)

stages:
- stage: 'Build'
  displayName: 'Build'
  dependsOn: 'Build'
  jobs:
  - template: 'Templates/build.yaml'
    parameters:
      dotNetVersion: $(dotNetVersion)
      applicationVersion: $(applicationVersion)
      angularApplicationPath: $(angularApplicationPath)
      apiApplicationPath: '$(Build.SourcesDirectory)/Site/Gmf.Marush.Care.Api'
      migrationsAssemblyPath: '$(Build.SourcesDirectory)/Site/Gmf.Marush.Care.Infrastructure'

- stage: 'DeployToTest'
  displayName: 'Deploy to Test'
  dependsOn: 'Build'
  condition:  succeeded()
  jobs:
  - template: 'Templates/environment-deploy.yaml'
    parameters:
      environment: 'Test'
      deploymentName: 'DeployAppToTest'
      destinationWebsiteName: MarushTest
  - template: 'Templates/environment-deploy.yaml'
    parameters:
      environment: 'Test'
      deploymentName: 'DeployApiToTest'
      destinationWebsiteName: MarushTest
      destinationWebsitePath: api
      archiveFile: 'Gmf.Marush.Care.Api.zip'
  - template: 'Templates/update-database.yaml'
    parameters:
      dbContextName: MarushCareContext
      migrationConnectionString: $(TestDatabaseConnectionString)
      environment: 'Test'
- stage: 'DeployToProduction'
  displayName: 'Deploy to Production'
  dependsOn: 'DeployToTest'
  condition:  succeeded()
  jobs:
  - job: WaitForValidation
    displayName: Wait for approval
    pool: server
    timeoutInMinutes: 21600 # job times out in 15 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 21600 # job times out in 15 days
      inputs:
        notifyUsers: |
          nizzotyphoon41@hotmail.com
        instructions: 'Please approve production deploy so it could be executed'
        onTimeout: reject
  - template: 'Templates/environment-deploy.yaml'
    parameters:
      environment: 'Production'
      deploymentName: 'DeployToProduction'
      approvalJobName: 'WaitForValidation'
      destinationWebsiteName: Marush
