trigger:
- main

pool:
  vmImage: windows-latest

variables:
  applicationVersion: 0.4

name: $(applicationVersion).$(Rev:r)

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - template: 'Templates/build.yaml'
    parameters:
      dotNetVersion: 8.0.100
      applicationVersion: $(applicationVersion)
      angularApplicationPath: 'Site/Gmf.Marush.Care.App'
      apiApplicationPath: 'Gmf.Marush.Care.Api'
      migrationsAssemblyPath: '../Gmf.Marush.Care.Infrastructure/Gmf.Marush.Care.Infrastructure.csproj'
- stage: 'DeployToTest'
  displayName: 'Deploy to Test'
  dependsOn: 'Build'
  condition:  succeeded()
  variables: 
    - group: Test
  jobs:
  - template: 'Templates/environment-deploy.yaml'
    parameters:
      environment: 'Test'
      deploymentName: 'App'
      destinationWebsiteName: MarushTest
  - template: 'Templates/environment-deploy.yaml'
    parameters:
      environment: 'Test'
      deploymentName: 'Api'
      destinationWebsiteName: MarushTest
      destinationWebsitePath: api
      archiveFile: 'Gmf.Marush.Care.Api.zip'
  - template: 'Templates/update-database.yaml'
    parameters:
      dbContextName: MarushCareContext
      migrationConnectionString: $(DatabaseConnectionString)
      environment: 'Test'
- stage: 'DeployToProduction'
  displayName: 'Deploy to Production'
  dependsOn: 'DeployToTest'
  condition:  succeeded()
  variables:
    DeployTimeout: 21600 # job times out in 15 days, can't be a variable
    - group: Production
  jobs:
  - job: WaitForValidation
    displayName: Wait for approval
    pool: server
    timeoutInMinutes: $(DeployTimeout)
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: $(DeployTimeout)
      inputs:
        notifyUsers: |
          nizzotyphoon41@hotmail.com
        instructions: 'Please approve production deploy so it could be executed'
        onTimeout: reject
  - template: 'Templates/environment-deploy.yaml'
    parameters:
      environment: 'Production'
      deploymentName: 'ProductionApp'
      destinationWebsiteName: Marush
      approvalJobName: 'WaitForValidation'
  - template: 'Templates/environment-deploy.yaml'
    parameters:
      environment: 'Production'
      deploymentName: 'ProductionApi'
      destinationWebsiteName: Marush
      destinationWebsitePath: api
      archiveFile: 'Gmf.Marush.Care.Api.zip'
  - template: 'Templates/update-database.yaml'
    parameters:
      dbContextName: MarushCareContext
      migrationConnectionString: $(DatabaseConnectionString)
      environment: 'Production'
